# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busca_diario', models.CharField(max_length=100, verbose_name='Busca diario')),
                ('data', models.DateTimeField(max_length=100, verbose_name='data')),
                ('busca_arquivo', models.CharField(max_length=100, verbose_name='Bucsa arquivo')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
                'ordering': ('-data',),
            },
        ),
    ]
