# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='nome_arquivo',
            field=models.CharField(default=-2017, max_length=100, verbose_name='Busca diario'),
            preserve_default=False,
        ),
    ]
