# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_pesquisa_nome_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='nome_arquivo',
            field=models.CharField(max_length=100, verbose_name='Nome arquivo'),
        ),
    ]
