# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_auto_20170620_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesquisa',
            options={'verbose_name': 'Pesquisa', 'verbose_name_plural': 'Pesquisas'},
        ),
    ]
