# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo_trabalhista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo_trabalhista',
            name='ano_processo',
            field=models.DateField(blank=True),
        ),
    ]
