# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo_trabalhista', '0002_auto_20170717_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo_trabalhista',
            name='ano_processo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
