# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo_trabalhista', '0003_auto_20170717_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento_trab',
            name='data_movimentacao',
            field=models.DateField(blank=True),
        ),
    ]
