# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizada', models.DateTimeField(blank=True)),
                ('tipo_distribuicao', models.CharField(max_length=1000)),
                ('comarca', models.CharField(max_length=1000)),
                ('secretaria', models.CharField(max_length=1000)),
                ('motivo', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(blank=True)),
                ('descricao', models.TextField(max_length=1000)),
                ('doc', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ('-data_movimentacao',),
            },
        ),
        migrations.CreateModel(
            name='Partes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte', models.CharField(max_length=1000)),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acervo', models.CharField(max_length=1000)),
                ('numero_processo', models.CharField(max_length=1000)),
                ('data_abertura', models.DateTimeField(blank=True)),
                ('comarca', models.CharField(max_length=1000)),
                ('assistencia_judiciaria', models.CharField(max_length=1000)),
                ('natureza', models.CharField(max_length=1000)),
                ('classe_processual', models.CharField(max_length=1000)),
                ('assuntos', models.CharField(max_length=1000)),
                ('observacao', models.CharField(max_length=1000)),
                ('valor_acao', models.CharField(max_length=1000)),
                ('status_atual', models.CharField(max_length=1000)),
                ('status_processo', models.BooleanField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partes',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Processo'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Processo'),
        ),
        migrations.AddField(
            model_name='distribuicao',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.Processo'),
        ),
    ]
