# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('apelido', models.CharField(blank=True, max_length=30)),
                ('nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('email', models.EmailField(max_length=300, verbose_name='E-mail')),
                ('rua', models.CharField(max_length=1000, verbose_name='Rua')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=50)),
                ('uf', models.CharField(choices=[('', 'Escolha uma Opção'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MT', 'Mato Grosso'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RS', 'Rio Grande do Sul'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('numero1', models.CharField(max_length=20, verbose_name='Telefone Principal')),
                ('numero2', models.CharField(blank=True, max_length=20, verbose_name='Telefone 2')),
            ],
            options={
                'ordering': ('-nome',),
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
            options={
                'verbose_name': 'Documento',
            },
        ),
        migrations.CreateModel(
            name='Trabalhista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctps', models.CharField(max_length=15, verbose_name='CTPS')),
                ('admissao', models.DateField(verbose_name='Admissão')),
                ('demissao', models.DateField(verbose_name='Demissão')),
                ('recisao', models.DateField(verbose_name='Recisão')),
                ('salario', models.CharField(max_length=20, verbose_name='Salário')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('entrada_manha', models.TimeField(verbose_name='Entrada(M)')),
                ('saida_manha', models.TimeField(verbose_name='Saída(M)')),
                ('entrada_tarde', models.TimeField(verbose_name='Entrada(T)')),
                ('saida_tarde', models.TimeField(verbose_name='Saída(T)')),
                ('seg', models.BooleanField(verbose_name='Seg')),
                ('ter', models.BooleanField(verbose_name='Ter')),
                ('qua', models.BooleanField(verbose_name='Qua')),
                ('qui', models.BooleanField(verbose_name='Qui')),
                ('sex', models.BooleanField(verbose_name='Sex')),
                ('sab', models.BooleanField(verbose_name='Sáb')),
                ('dom', models.BooleanField(verbose_name='Dom')),
                ('obs_semana', models.TextField(verbose_name='Observação Horário')),
                ('hor_con', models.BooleanField(verbose_name='Controle de horário')),
                ('ponto', models.CharField(choices=[('Cartão', 'Cartão'), ('Folha', 'Livro'), ('Eletrônico', 'Eletrônico'), ('Outros', 'Outros')], max_length=100, verbose_name='Ponto')),
                ('obs_ponto', models.TextField(verbose_name='Observação Ponto')),
                ('pergunta1', models.CharField(max_length=100, verbose_name='Quem marcava o ponto')),
                ('pergunta2', models.BooleanField(verbose_name='Marcava no mesmo horário')),
                ('pergunta3', models.BooleanField(verbose_name='Marcava o horário correto')),
                ('hora_intineri', models.BooleanField(verbose_name='Hora Intineri')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
            options={
                'verbose_name': 'Trabalhista',
                'verbose_name_plural': 'Trabalhistas',
            },
        ),
    ]
