# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.DateField(null=True)),
                ('valor_total', models.CharField(max_length=20)),
                ('n_parcela', models.IntegerField(blank=True, choices=[(0, 'Escolha uma opção'), (1, '1x'), (2, '2x'), (3, '3x'), (4, '4x'), (5, '5x'), (6, '6x'), (7, '7x'), (8, '8x'), (9, '9x'), (10, '10x'), (11, '11x'), (12, '12x')], default=0)),
                ('status_pag', models.BooleanField(default=False)),
                ('forma_pagamento', models.CharField(choices=[('', 'Escolha uma opção'), ('á vista', 'á vista'), ('Cartão de credito', 'Cartão de credito'), ('Boleto', 'Boleto'), ('Cheque', 'Cheque')], max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('valor_entrada', models.CharField(default=0, max_length=20)),
                ('valor_parcela', models.CharField(default=0, max_length=20)),
            ],
            options={
                'verbose_name': 'Conta',
                'ordering': ('-vencimento',),
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.DateField()),
                ('status_pag', models.BooleanField(default=False)),
                ('data_pag', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
            },
        ),
        migrations.CreateModel(
            name='Conta_pagar',
            fields=[
                ('conta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.Conta')),
                ('conta_fixa', models.NullBooleanField(default=False)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('observacao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Conta à pagar',
                'verbose_name_plural': 'Contas à pagar',
            },
            bases=('financeiro.conta',),
        ),
        migrations.CreateModel(
            name='Conta_receber',
            fields=[
                ('conta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financeiro.Conta')),
                ('descricao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('observacao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Conta à receber',
                'verbose_name_plural': 'Contas à receber',
            },
            bases=('financeiro.conta',),
        ),
        migrations.AddField(
            model_name='parcela',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Conta'),
        ),
        migrations.AddField(
            model_name='conta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.Categoria'),
        ),
    ]
