# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
