# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20170502_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Categoria'),
        ),
    ]
