# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-21 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20170512_1813'),
        ('financeiro', '0005_auto_20170502_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta_receber',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processos.Processo'),
        ),
    ]
